controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

send_notification:
    path: /send-notification
    controller: App\Controller\PusherController::sendNotification